### ISSUE TITLE
Mencoder replacement

### ISSUE THREAD

**Issue by skerit** [andyrblank/Commercial-Clapboard#2]
Mencoder seems to be dead in the water, and hasn't been in the ubuntu repos for a few versions now.
Any idea as to what to use in its place?

Ffmpeg seems like a logical choice, but it has no EDL support. You can't even specify frames while cutting, but need to provide seconds.

**Comment by andyrblank** [comment]
I wish I had a good answer for you but I left this project a while ago after issues with my tuner card. Honestly though looking back at this script Mencoder was really just a small piece that cut the commercials out of the video and it did the best out of what I tried so that's why I chose it. Compiling Mencoder from source is always an option. Maybe not what you want to hear but that's probably what I would do if I were still working on this.

**Comment by andyrblank** [comment]
Or there's this solution: http://askubuntu.com/questions/595978/how-to-install-mencoder-in-ubuntu-14-10

**Comment by skerit** [comment]
Thanks for the link, but messing with those libav packages messes up a lot of things :P

I'll probably write a little script to use ffmpeg via some way. Thanks for the response!

**Comment by andyrblank** [comment]
No problem. If you come up with something cool let me know!
